
FROM continuumio/miniconda3
LABEL maintainer='scanflow'

RUN pip install mlflow==1.14.1
RUN pip install fastapi
RUN pip install uvicorn
RUN pip install aiohttp
RUN pip install aiodns

ENV AGENT_PORT  8005
ENV AGENT_HOME  /checker/agent

RUN useradd -m -d /checker checker
RUN mkdir -p $AGENT_HOME
RUN chown -R checker /checker
USER checker
WORKDIR $AGENT_HOME

CMD uvicorn checker_agent:app --reload --host 0.0.0.0 --port $AGENT_PORT

