
FROM continuumio/miniconda3
LABEL maintainer='scanflow'

COPY req_modeling.txt req_modeling.txt
RUN pip install -r req_modeling.txt

RUN useradd -m -d /executor executor
RUN chown -R executor /executor
USER executor
WORKDIR /executor

