
FROM continuumio/miniconda3:latest
LABEL maintainer=scanflow

RUN useradd --create-home --shell /bin/bash dev
WORKDIR /home/dev
RUN chown -R dev: /opt/conda
USER dev

RUN pip install mlflow==1.16.0

RUN mkdir -p /home/dev/executor
COPY req_detector.txt req_detector.txt
RUN pip install -r req_detector.txt
RUN echo "Executor = detector-training was built successfully."
