
FROM training-mnist-training

RUN pip install opyrator==0.0.12

RUN mkdir -p /home/dev/predictor
WORKDIR /home/dev/predictor

ENV PREDICTOR_PORT  8010
CMD opyrator launch-api predictor:main --port $PREDICTOR_PORT

