
FROM continuumio/miniconda3:latest
LABEL maintainer=scanflow

RUN useradd --create-home --shell /bin/bash dev
WORKDIR /home/dev
RUN chown -R dev: /opt/conda
USER dev

RUN pip install mlflow==1.16.0

ENV MLFLOW_HOST  0.0.0.0
ENV MLFLOW_PORT  8002
ENV MLFLOW_BACKEND  sqlite:////home/dev/mlflow/backend.sqlite
ENV MLFLOW_ARTIFACT  /home/dev/mlflow/mlruns

RUN mkdir -p /home/dev/mlflow
RUN mkdir -p $MLFLOW_ARTIFACT

CMD mlflow server                  --backend-store-uri $MLFLOW_BACKEND                 --default-artifact-root $MLFLOW_ARTIFACT                 --host $MLFLOW_HOST -p $MLFLOW_PORT
