
FROM continuumio/miniconda3
LABEL maintainer='scanflow'

RUN pip install mlflow==1.14.1
RUN chmod -R 777 /opt/conda/

ENV PREDICTOR_PORT  8010
ENV PREDICTOR_HOME  /predictor
RUN useradd -m -d /predictor predictor
RUN mkdir -p $PREDICTOR_HOME
RUN chown -R predictor /predictor
USER predictor
WORKDIR $PREDICTOR_HOME/workflow
CMD mlflow models serve -m "models:/mnist_cnn/1" --host 0.0.0.0 --port $PREDICTOR_PORT

