
FROM continuumio/miniconda3:latest
LABEL maintainer=scanflow

RUN useradd --create-home --shell /bin/bash dev
WORKDIR /home/dev
RUN chown -R dev: /opt/conda
USER dev

RUN pip install mlflow==1.16.0

RUN pip install fastapi==0.64.0
RUN pip install uvicorn==0.13.4
RUN pip install aiohttp==3.7.4
RUN pip install aiodns==2.0.0

ENV AGENT_PORT  8005
ENV AGENT_HOME  /home/dev/improver/agent

RUN mkdir -p /home/dev/improver
RUN mkdir -p $AGENT_HOME

WORKDIR $AGENT_HOME

CMD uvicorn improver_agent:app --reload --host 0.0.0.0 --port $AGENT_PORT
