
FROM continuumio/miniconda3
LABEL maintainer='scanflow'

COPY req_training.txt req_training.txt
RUN pip install -r req_training.txt

RUN useradd -m -d /executor executor
RUN chown -R executor /executor
USER executor
WORKDIR /executor

