
FROM continuumio/miniconda3
LABEL maintainer='scanflow'

ENV MLFLOW_HOME  /mlflow
ENV MLFLOW_HOST  0.0.0.0
ENV MLFLOW_PORT  8002
ENV MLFLOW_BACKEND  sqlite:////mlflow/backend.sqlite
ENV MLFLOW_ARTIFACT  /mlflow/mlruns

RUN pip install mlflow==1.14.1

RUN useradd -m -d /mlflow mlflow
RUN mkdir -p $MLFLOW_ARTIFACT
RUN chown -R mlflow /mlflow
USER mlflow
WORKDIR /mlflow

WORKDIR $MLFLOW_HOME

CMD mlflow server                  --backend-store-uri $MLFLOW_BACKEND                 --default-artifact-root $MLFLOW_ARTIFACT                 --host $MLFLOW_HOST -p $MLFLOW_PORT

