
FROM continuumio/miniconda3
LABEL maintainer='scanflow'

RUN pip install tensorflow==2.4.1
RUN pip install mlflow==1.14.1

RUN useradd -m -d /checker checker
RUN chown -R checker /checker
USER checker
WORKDIR /checker

