
FROM continuumio/miniconda3
LABEL maintainer='scanflow'

COPY req_predictor.txt req_predictor.txt
RUN pip install -r req_predictor.txt

RUN useradd -m -d /executor executor
RUN chown -R executor /executor
USER executor
WORKDIR /executor

