
FROM continuumio/miniconda3
LABEL maintainer='scanflow'

RUN pip install mlflow==1.14.1
RUN pip install fastapi
RUN pip install uvicorn
RUN pip install aiohttp
RUN pip install aiodns

ENV AGENT_PORT  8007
ENV AGENT_HOME  /planner/agent

RUN useradd -m -d /planner planner
RUN mkdir -p $AGENT_HOME
RUN chown -R planner /planner
USER planner
WORKDIR $AGENT_HOME

CMD uvicorn planner_agent:app --reload --host 0.0.0.0 --port $AGENT_PORT

